x-common-build-args: &common-build-args
  ARCH_IMAGE_DIGEST: sha256:5ba8bb318666baef4d33afefc0e65db80f38b23503cb8e7b150d315cc2d4d5da
  CACHYOS_COMMIT_HASH: 063f193f1983df869e1884466b84d8fa13e5fce5
  KERNEL_COMMIT_HASH: 188f42461a55082eb465ddadad08225de6be07e6

services:
  kernel-config:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kernel
      args:
        <<: *common-build-args
    image: kernel-toolchain
    container_name: kernel-config
    volumes:
      - ./profiles:/profiles
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-cachyos
        cp -a /src/. /build/linux-cachyos/
        cd /build/linux-cachyos/linux-cachyos
        chown -R builder:builder /profiles /build
        su builder -c "
          updpkgsums
          makepkg -o
          cd /build/linux-cachyos/linux-cachyos/src/cachyos-*/
          cp /build/linux-cachyos/linux-cachyos/config-*-bore-lto-afdo-propeller .config
          LLVM=1 LLVM_IAS=1 make menuconfig
          cp .config /profiles/
        "

  kernel-builder:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kernel
      args:
        <<: *common-build-args
    image: kernel-toolchain
    container_name: kernel-builder
    volumes:
      - ./out:/out
      - ./profiles/.config:/profiles/.config
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-cachyos
        cp -a /src/. /build/linux-cachyos/
        cd /build/linux-cachyos/linux-cachyos
        cp /profiles/.config config
        chown -R builder:builder /out /build
        su builder -c "
          updpkgsums
          makepkg -s --noconfirm --skippgpcheck
          cp -v *.pkg.tar.zst /out/
        "
