x-common-build-args: &common-build-args
  ARCH_IMAGE_DIGEST: sha256:5ba8bb318666baef4d33afefc0e65db80f38b23503cb8e7b150d315cc2d4d5da
  UBUNTU_IMAGE_DIGEST: sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b
  CACHYOS_COMMIT_HASH: 063f193f1983df869e1884466b84d8fa13e5fce5
  KERNEL_COMMIT_HASH: 1c61dfd1c3ad7762faa0db8b06c6af6c59cc4340
  PROPELLER_COMMIT_HASH: e7a831e46e8822f00d0fb9082486745c62748a7e
  LLVM_GPG_FINGERPRINT: 6084F3CF814B57C1CF12EFD515CF4D18AF4F7421

services:
  kernel-autofdo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kernel
      args:
        <<: *common-build-args
        FLAVOR: autofdo
    image: kernel-autofdo
    container_name: kernel-autofdo
    volumes:
      - ./out:/out
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-cachyos /out/autofdo
        cp -a /src/. /build/linux-cachyos/
        cd /build/linux-cachyos/linux-cachyos
        chown -R builder:builder /build /out
        su builder -c "
          updpkgsums
          makepkg -o
          cp /build/linux-cachyos/linux-cachyos/config-*-cachyos config
          updpkgsums
          makepkg -s --noconfirm --skippgpcheck
          cp -v *.pkg.tar.zst /out/autofdo/
        "

  autofdo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.autofdo
      args:
        <<: *common-build-args
    image: autofdo
    container_name: autofdo
    privileged: true
    pid: "host"
    volumes:
      - ./profiles:/profiles
      - ./out:/out
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        cd /build
        perf record --pfm-events RETIRED_TAKEN_BRANCH_INSTRUCTIONS:k -a -N -b -c 500009 -o kernel.data sleep 1200
        mkdir -p extract_dbg
        tar --use-compress-program=zstd -xvf /out/autofdo/linux-cachyos-dbg-*.pkg.tar.zst -C extract_dbg
        llvm-profgen --kernel --binary=extract_dbg/usr/src/debug/linux-cachyos/vmlinux --perfdata=kernel.data -o /profiles/kernel.afdo

  kernel-propeller:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kernel
      args:
        <<: *common-build-args
        FLAVOR: propeller
    image: kernel-propeller
    container_name: kernel-propeller
    volumes:
      - ./out:/out
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-cachyos /out/propeller
        cp -a /src/. /build/linux-cachyos/
        cd /build/linux-cachyos/linux-cachyos
        chown -R builder:builder /build /out
        su builder -c "
          updpkgsums
          makepkg -o
          cp /build/linux-cachyos/linux-cachyos/config-*-cachyos config
          updpkgsums
          makepkg -s --noconfirm --skippgpcheck
          cp -v *.pkg.tar.zst /out/propeller/
        "

  propeller:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.propeller
      args:
        <<: *common-build-args
    image: propeller
    container_name: propeller
    privileged: true
    pid: "host"
    volumes:
      - ./profiles:/profiles
      - ./out:/out
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        cd /build
        perf record --pfm-events RETIRED_TAKEN_BRANCH_INSTRUCTIONS:k -a -N -b -c 500009 -o kernel.data sleep 1200
        mkdir -p extract_dbg
        tar --use-compress-program=zstd -xvf /out/autofdo/linux-cachyos-dbg-*.pkg.tar.zst -C extract_dbg
        generate_propeller_profiles --binary=extract_dbg/usr/src/debug/linux-cachyos/vmlinux --profile=kernel.data --cc_profile=/profiles/propeller_cc_profile.txt --ld_profile=/profiles/propeller_ld_profile.txt        

  kernel-config:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kernel
      args:
        <<: *common-build-args
        FLAVOR: kernel
    image: kernel-toolchain
    container_name: kernel-config
    volumes:
      - ./profiles:/profiles
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-cachyos
        cp -a /src/. /build/linux-cachyos/
        cd /build/linux-cachyos/linux-cachyos
        chown -R builder:builder /profiles /build
        su builder -c "
          updpkgsums
          makepkg -o
          cd /build/linux-cachyos/linux-cachyos/src/cachyos-*/
          cp /build/linux-cachyos/linux-cachyos/config-*-eevdf-lto-afdo-propeller .config
          LLVM=1 LLVM_IAS=1 make menuconfig
          cp .config /profiles/
        "

  kernel-builder:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kernel
      args:
        <<: *common-build-args
        FLAVOR: kernel
    image: kernel-toolchain
    container_name: kernel-builder
    volumes:
      - ./out:/out
      - ./profiles/.config:/profiles/.config
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-cachyos
        cp -a /src/. /build/linux-cachyos/
        cd /build/linux-cachyos/linux-cachyos
        cp /profiles/.config config
        chown -R builder:builder /out /build
        su builder -c "
          updpkgsums
          makepkg -s --noconfirm --skippgpcheck
          cp -v *.pkg.tar.zst /out/
        "