x-common-build-args: &common-build-args
  ARCH_IMAGE_DIGEST: sha256:ceac417c19645d21630c120fa123942aa1fc5988faab14e67222013cb11f31bb
  UBUNTU_IMAGE_DIGEST: sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b
  CACHYOS_REPO_FLAVOR: auto
  KERNEL_COMMIT_HASH: e625438b981d774a22e2ba431a2d93e1737462ff
  PROPELLER_COMMIT_HASH: e7a831e46e8822f00d0fb9082486745c62748a7e
  LLVM_GPG_FINGERPRINT: 6084F3CF814B57C1CF12EFD515CF4D18AF4F7421

x-common-tmpfs: &common-tmpfs
  - /build:rw,exec,size=64G,mode=1777

x-kernel-build: &kernel-build
  context: .
  dockerfile: ./Dockerfile
  target: kernel-toolchain
  args:
    <<: *common-build-args

x-profiler-build: &profiler-build
  context: .
  dockerfile: ./Dockerfile
  args:
    <<: *common-build-args

x-kernel-service: &kernel-service
  tmpfs: *common-tmpfs
  volumes:
    - ./scripts:/scripts:ro

x-profile-service: &profile-service
  privileged: true
  pid: "host"
  tmpfs: *common-tmpfs
  volumes:
    - ./scripts:/scripts:ro
    - ./profiles:/profiles
    - ./out:/out

services:
  kernel-autofdo:
    <<: *kernel-service
    build:
      <<: *kernel-build
      args:
        <<: *common-build-args
        FLAVOR: autofdo
    image: kernel-autofdo
    container_name: kernel-autofdo
    volumes:
      - ./scripts:/scripts:ro
      - ./out:/out
    command:
      - bash
      - /scripts/build-cachyos-package.sh
      - autofdo

  autofdo:
    <<: *profile-service
    build:
      <<: *profiler-build
      target: autofdo-profiler
    image: autofdo
    container_name: autofdo
    command:
      - bash
      - /scripts/generate-autofdo-profile.sh

  kernel-propeller:
    <<: *kernel-service
    build:
      <<: *kernel-build
      args:
        <<: *common-build-args
        FLAVOR: propeller
    image: kernel-propeller
    container_name: kernel-propeller
    volumes:
      - ./scripts:/scripts:ro
      - ./out:/out
    command:
      - bash
      - /scripts/build-cachyos-package.sh
      - propeller

  propeller:
    <<: *profile-service
    build:
      <<: *profiler-build
      target: propeller-profiler
    image: propeller
    container_name: propeller
    command:
      - bash
      - /scripts/generate-propeller-profile.sh

  kernel-config:
    <<: *kernel-service
    build:
      <<: *kernel-build
      args:
        <<: *common-build-args
        FLAVOR: kernel
    image: kernel-toolchain
    container_name: kernel-config
    volumes:
      - ./scripts:/scripts:ro
      - ./patches:/patches
    command:
      - bash
      - /scripts/generate-config-patch.sh

  kernel-builder:
    <<: *kernel-service
    build:
      <<: *kernel-build
      args:
        <<: *common-build-args
        FLAVOR: kernel
    image: kernel-toolchain
    container_name: kernel-builder
    volumes:
      - ./scripts:/scripts:ro
      - ./out:/out
      - ./patches/config.patch:/patches/config.patch:ro
    command:
      - bash
      - /scripts/build-custom-kernel.sh
