services:
  kernel-config:
    build:
      context: .
    image: cachyos-toolchain
    container_name: kernel-config
    volumes:
      - ./conf:/conf
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-cachyos
        cp -a /src/. /build/linux-cachyos/
        cd /build/linux-cachyos/linux-cachyos
        chown -R builder:builder /conf /build
        su builder -c "
          updpkgsums
          makepkg -o
          cd /build/linux-cachyos-bore-lto/src/cachyos-*/
          cp /build/linux-cachyos/linux-cachyos/config-*-cachyos-bore-lto .config
          make menuconfig
          cp .config /conf/
        "

  kernel-builder:
    build:
      context: .
    image: cachyos-toolchain
    container_name: kernel-builder
    volumes:
      - ./out:/out
      - ./conf/.config:/tmp/.config:ro
    tmpfs:
      - /build:rw,exec,size=64G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-cachyos
        cp -a /src/. /build/linux-cachyos/
        cd /build/linux-cachyos/linux-cachyos
        cp /tmp/.config config
        chown -R builder:builder /out /build
        su builder -c "
          updpkgsums
          makepkg -s --noconfirm --skippgpcheck
          cp -v *.pkg.tar.zst /out/
        "