x-common-build-args: &common-build-args
  DEBIAN_IMAGE_DIGEST: sha256:109e2c65005bf160609e4ba6acf7783752f8502ad218e298253428690b9eaa4b
  COMMIT_HASH: a72a0085aeac23ac8aa76c90c476e20626046ea7

x-common-vars: &common-vars
  ARCH: arm64

x-kernel-service: &kernel-service
  platform: "linux/arm64"
  build:
    context: .
    args:
      <<: *common-build-args
  image: rpi-toolchain
  environment: *common-vars
  tmpfs:
    - /build:rw,exec,size=12G,mode=1777

services:
  kernel-config:
    <<: *kernel-service
    container_name: kernel-config
    volumes:
      - ./scripts:/scripts:ro
      - ./patches:/patches
    command:
      - bash
      - /scripts/generate-config-patch.sh

  kernel-builder:
    <<: *kernel-service
    container_name: kernel-builder
    volumes:
      - ./scripts:/scripts:ro
      - ./out:/out
      - ./patches/config.patch:/patches/config.patch:ro
    command:
      - bash
      - /scripts/build-custom-kernel.sh
