x-common-variables: &common-vars
  COMMIT_HASH: e7a3953084a7050ca349010deb22546834c2e196

services:
  kernel-config:
    build:
      context: .
    image: rpi-toolchain
    container_name: kernel-config
    environment: *common-vars
    stdin_open: true
    tty: true
    volumes:
      - ./conf:/conf
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-rpi
        cd /build/linux-rpi
        git init
        git remote add origin https://github.com/raspberrypi/linux.git
        git fetch --depth 1 origin "${COMMIT_HASH}"
        git checkout FETCH_HEAD
        export LLVM=1
        export KERNEL=kernel_2712
        make bcm2712_defconfig
        make menuconfig
        sudo cp .config /conf/.config

  kernel-builder:
    build:
      context: .
    image: rpi-toolchain
    container_name: kernel-builder
    environment: *common-vars
    volumes:
      - ./out:/out
      - ./conf/.config:/tmp/.config:ro
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        mkdir -p /build/linux-rpi
        cd /build/linux-rpi
        git init
        git remote add origin https://github.com/raspberrypi/linux.git
        git fetch --depth 1 origin "${COMMIT_HASH}"
        git checkout FETCH_HEAD
        cp /tmp/.config .config
        export LLVM=1
        export KERNEL=kernel_2712
        make -j$(nproc) Image.gz modules dtbs KCFLAGS="-mcpu=native"
        make -j$(nproc) INSTALL_MOD_PATH=/out modules_install
        sudo mkdir -p /out/overlays
        sudo cp arch/arm64/boot/Image /out/kernel_2712.img
        sudo cp arch/arm64/boot/dts/broadcom/*.dtb /out/
        sudo cp arch/arm64/boot/dts/overlays/*.dtbo /out/overlays/
        sudo cp arch/arm64/boot/dts/overlays/README /out/overlays/