x-llama-build-args: &llama-build-args
  BASE_CUDA_DEV_CONTAINER: nvidia/cuda@sha256:44a9504c6dfb50b1241464241b02a93871928f373de6f5a644cf5fe9f080aa63 # nvidia/cuda version: 13.2.1-devel-ubuntu24.04
  LLAMA_CPP_REPO: https://github.com/ggml-org/llama.cpp.git
  LLAMA_CPP_COMMIT: 1e5ad35d560b90a8ac447d149c8f8447ae1fcaa0
  CUDA_ARCH: 89-real
  CUDA_COMPRESSION_MODE: speed

x-model-volume: &model-volume
  type: bind
  source: ./models
  target: /models

x-llama-service: &llama-service
  build:
    context: .
    dockerfile: Dockerfile
    args: *llama-build-args
  env_file:
    - ${LLAMA_ENV_FILE:-.env}
  user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
  gpus: all
  ipc: host
  ulimits:
    memlock: -1
    stack: 67108864
  working_dir: /models
  environment:
    NVIDIA_VISIBLE_DEVICES: all
    NVIDIA_DRIVER_CAPABILITIES: compute,utility
    HOME: /models/home
    XDG_CACHE_HOME: /models/.cache
    HF_HOME: /models/hf-home
    HUGGINGFACE_HUB_CACHE: /models/hf-home/hub
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  volumes:
    - *model-volume

services:
  llama-server:
    <<: *llama-service
    build:
      context: .
      dockerfile: Dockerfile
      target: server
      args: *llama-build-args
    image: llama-server
    container_name: llama-server
    ports:
      - 127.0.0.1:${LLAMA_ARG_PORT:-8080}:${LLAMA_ARG_PORT:-8080}
