x-common-build-args: &common-build-args
  ARCH_IMAGE_DIGEST: sha256:1047e6e7878d58e4ee47e1cd6459a32fab41246b0efc4109e11b7ef16f50b14d
  CACHYOS_REPO_FLAVOR: auto
  KERNEL_COMMIT_HASH: 791fb8ea6d3cf7c85e596678c25c56fa140591be

x-common-tmpfs: &common-tmpfs
  - /build:rw,exec,size=64G,mode=1777

x-kernel-build: &kernel-build
  context: .
  dockerfile: ./Dockerfile
  target: kernel-toolchain
  args:
    <<: *common-build-args

x-profiler-build: &profiler-build
  context: .
  dockerfile: ./Dockerfile
  args:
    <<: *common-build-args

x-kernel-service: &kernel-service
  tmpfs: *common-tmpfs
  volumes:
    - ./scripts:/scripts:ro

x-profile-service: &profile-service
  privileged: true
  pid: "host"
  tmpfs: *common-tmpfs
  volumes:
    - ./scripts:/scripts:ro
    - ./profiles:/profiles
    - ./out:/out

services:
  kernel-autofdo:
    <<: *kernel-service
    build:
      <<: *kernel-build
      args:
        <<: *common-build-args
        FLAVOR: autofdo
    image: kernel-autofdo
    container_name: kernel-autofdo
    volumes:
      - ./scripts:/scripts:ro
      - ./out:/out
    command:
      - bash
      - /scripts/build-cachyos-package.sh
      - autofdo

  autofdo:
    <<: *profile-service
    build:
      <<: *profiler-build
      target: autofdo-profiler
    image: autofdo
    container_name: autofdo
    command:
      - bash
      - /scripts/generate-autofdo-profile.sh

  kernel-config:
    <<: *kernel-service
    build:
      <<: *kernel-build
      args:
        <<: *common-build-args
        FLAVOR: kernel
    image: kernel-toolchain
    container_name: kernel-config
    volumes:
      - ./scripts:/scripts:ro
      - ./patches:/patches
    command:
      - bash
      - /scripts/generate-config-patch.sh

  kernel-builder:
    <<: *kernel-service
    build:
      <<: *kernel-build
      args:
        <<: *common-build-args
        FLAVOR: kernel
    image: kernel-toolchain
    container_name: kernel-builder
    volumes:
      - ./scripts:/scripts:ro
      - ./out:/out
      - ./patches/config.patch:/patches/config.patch:ro
    command:
      - bash
      - /scripts/build-custom-kernel.sh
